language: php

php:
  - 5.5.9
  - 7

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text
