language: php

php:
  - 5.5.9

before_script:
  - composer update
  - composer require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - phpunit --coverage-text

after_success:
  - travis_retry php vendor/bin/coveralls